version: "3.4"
services:
  selenium-hub:
    image: jonnyman9/selenium-hub
    ports:
      - "4444:4444"
    healthcheck:
      test: ["CMD", "/opt/bin/check-grid.sh", "--host", "0.0.0.0", "--port", "4444"]
      interval: 15s
      timeout: 15s
      retries: 3
      start_period: 30s

  chrome:
    image: jonnyman9/selenium-node-chrome
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - NODE_PORT=5555
      - JAVA_OPTS=-Dwebdriver.chrome.whitelistedIps
    ports:
      - "5555:5555"
    healthcheck:
      test: ["CMD", "/opt/bin/check-grid.sh", "--host", "0.0.0.0", "--port", "5555"]
      interval: 15s
      timeout: 15s
      retries: 5
      start_period: 30s
    depends_on:
      - selenium-hub
