#!/bin/bash

CHROME_VERSION=$(/usr/bin/google-chrome -version | awk '{ print $3 }')

cat <<_EOF
{
  "capabilities": [
    {
      "version": "85",
      "browserName": "chrome",
      "maxInstances": 1,
      "seleniumProtocol": "WebDriver",
      "applicationName": "TSSC UAT"
    }
  ],
  "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
  "maxSession": 1,
  "host": 0.0.0.0
  "port": 5555,
  "register": true,
  "registerCycle": 5000,
  "nodePolling": 5000,
  "unregisterIfStillDownAfter": 60000,
  "downPollingLimit": 2,
  "debug": false
}
_EOF
